# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84f16f84785c32781212c64a078389e917be22df31e3d42c987c2fc0da2d8df1d941ec1aa5d44231bf2dfffdd3e3ff0a238953e9d27fa26496ad1d54c10c7dce

test:
  secret_key_base: 2f8991f7f4a7d0987786879e0a44825bdd425f0dac0b853e4cd38e7587e98be714b2925d6a25b59565700479b12fecc20ea7293659c0fb70e2a645bef8df92c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
